In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5,6]
print("List:",a,type(a),sep="\n")
b = np.array(a)
print("numpy array:",b,type(b),sep="\n")

List:
[1, 2, 3, 4, 5, 6]
<class 'list'>
numpy array:
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
# np.zeros(shape,dtype='float',order='C')
# order 'C' is row major ordering
# order 'F' is column major ordering
np.zeros((2,3),dtype='int',order='C')
# dtype default is float can use int 

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
# the difference between arange and linspace is 
print("arange:",np.arange(0,10,2))
# in arange there will be stepcount
# in linspace the numbers in ndarray is evenly spaced based on what we give
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0) -> tuple | Any
b=np.linspace(0,10,2,dtype='int')
print("linspace:",b)
np.linspace(0, 10, num=13, dtype='int',endpoint=False,retstep=True,axis=0)
c=np.linspace(0, 10, 13, dtype='int',endpoint=False,axis=-1)
print(c)
np.linspace(0, 10, 13, dtype='int',endpoint=False,retstep=True,axis=0)


arange: [0 2 4 6 8]
linspace: [ 0 10]
[0 0 1 2 3 3 4 5 6 6 7 8 9]


(array([0, 0, 1, 2, 3, 3, 4, 5, 6, 6, 7, 8, 9]), 0.7692307692307693)

### like linspace there are 
### geomspace where number evenly spaced on a log scale (a geometric progression)
### logspacenumber evenly spaced on log scale

In [6]:
# identity matrix
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [7]:
# rand will get values of random numbers of uniform distribution
# range [0,1)
print(np.random.rand(2,3))
np.random.rand(3)

[[0.70449465 0.92270007 0.59906649]
 [0.22089557 0.57055524 0.88886986]]


array([0.14790906, 0.4834648 , 0.58195403])

In [8]:
# randn is standard normal distribution where mean is 0 and S.D is 1
# this will have negative numbers too
print(np.random.randn(3))
print(np.random.randn(2,3))


[-0.41353867  0.04802035 -1.21554156]
[[-0.21223083  0.58304971 -0.63997977]
 [-0.22034083  0.55292943  0.94200487]]


In [9]:
# np.random.randint(low, high=..., size=..., dtype=...)
print(np.random.randint(0, 101,(2,3)))
np.random.randint(0,101,5)


[[75 34 13]
 [19 83 12]]


array([90, 42, 77, 94, 72])

## random.seed is used to get the same values in case u need it again
### see below three cells

In [10]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [11]:
np.random.rand(4)


array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [12]:
np.random.seed(42)
np.random.rand(4)
# the below value is same as the output of above cell i.e first cell of random.seed

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [13]:
arr = np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
randarray = np.random.randint(0,101,10)
print(randarray)
print(randarray.max())
randarray.min()

[82 86 74 74 87 99 23  2 21 52]
99


2

In [15]:
# the argmax gives the index location of the max value
print(randarray.argmin())
randarray.argmax()


7


5

In [17]:
arr = np.arange(0,11)
arr[8]

8

In [18]:
arr[5:10]

array([5, 6, 7, 8, 9])

In [19]:
arr[:5]

array([0, 1, 2, 3, 4])

In [20]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr[0:5]=100

In [23]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [24]:
arr = np.arange(0,11)

In [25]:
slice_of_arr = arr[0:5]

In [26]:
slice_of_arr[:]=99

In [27]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [28]:
arr_copy = arr.copy()

In [31]:
arr_copy[:]=200
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [32]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

### 2D arrays

In [33]:
arr_2d = np.array([[5,10,15],[10,20,30],[500,1000,2000]])

In [34]:
arr_2d

array([[   5,   10,   15],
       [  10,   20,   30],
       [ 500, 1000, 2000]])

In [37]:
arr_2d.shape

(3, 3)

In [38]:
arr_2d[1][1]

20

In [39]:
arr_2d[1,1]

20

In [41]:
arr_2d[:2,1:]

array([[10, 15],
       [20, 30]])

In [49]:
arr =np.arange(1,11)
arr[6]=3

In [50]:
arr>4

array([False, False, False, False,  True,  True, False,  True,  True,
        True])

In [44]:
bool_arr = arr>4

In [45]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [54]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2,
                       1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = len(dice_rolls[dice_rolls > 2])
print(total_rolls_over_two)


19


In [55]:
total_rolls_over_two = dice_rolls > 2

dice_rolls[total_rolls_over_two]

len(dice_rolls[total_rolls_over_two])
print(total_rolls_over_two)


[ True False  True False  True False False  True False  True False False
  True  True  True  True  True False  True False  True  True  True  True
 False  True  True  True  True]


In [56]:
arr = np.arange(0,11)

In [57]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [59]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [60]:
# 0/0 in numpy gives nan = not a number
# 1/0 in numpy gives inf = infinity
arr/0

array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [61]:
arr/arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [63]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [65]:
print(arr.sum())
np.sum(arr)

55


55

In [66]:
arr.mean()

5.0

In [68]:
arr.std()

3.1622776601683795

In [69]:
arr.var()

10.0

In [5]:
b = np.arange(0,25).reshape(5,5)

In [6]:
# b = b.reshape(5,5)

In [7]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
b.ndim
# shows dimension of matrix here it is 2D matrix

2

In [13]:
b=b.T
# transpose

In [14]:
np.linalg.det(b)
# to find determinant of matrix

0.0

In [15]:
np.linalg.matrix_rank(b)
# rank of matrix

2

In [20]:
b

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [23]:
print(np.diag(b))
b.diagonal()

[ 0  6 12 18 24]


array([ 0,  6, 12, 18, 24])

In [24]:
print(np.diag(b,k=1))
b.diagonal(offset=1)

# diagnol of above


[ 5 11 17 23]


array([ 5, 11, 17, 23])

In [19]:
# diagonal of below
b.diagonal(offset=-1)

array([ 1,  7, 13, 19])

In [22]:
np.diag(b)

array([ 0,  6, 12, 18, 24])

In [21]:
# to get negative diagonal we need to rotate the matrix
# ? https://stackoverflow.com/questions/16114333/getting-the-opposite-diagonal-of-a-numpy-array
np.diag(np.fliplr(b))


array([20, 16, 12,  8,  4])

In [25]:
b.trace()
# sum of elements on the principal diagonal

60

In [74]:
b.sum()

300

In [75]:
b.sum(axis=0)  # sum across rows i.e 0+1+2+3+4

array([50, 55, 60, 65, 70])

In [76]:
b.sum(axis=1)  # sum across columns i.e 0+5+10+15+20

array([ 10,  35,  60,  85, 110])