In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5,6]
print("List:",a,type(a),sep="\n")
b = np.array(a)
print("numpy array:",b,type(b),sep="\n")

List:
[1, 2, 3, 4, 5, 6]
<class 'list'>
numpy array:
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
# np.zeros(shape,dtype='float',order='C')
# order 'C' is row major ordering
# order 'F' is column major ordering
np.zeros((2,3),dtype='int',order='C')
# dtype default is float can use int 

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# the difference between arange and linspace is 
print("arange:",np.arange(0,10,2))
# in arange there will be stepcount
# in linspace the numbers in ndarray is evenly spaced based on what we give
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0) -> tuple | Any
b=np.linspace(0,10,2,dtype='int')
print("linspace:",b)
np.linspace(0, 10, num=13, dtype='int',endpoint=False,retstep=True,axis=0)
c=np.linspace(0, 10, 13, dtype='int',endpoint=False,axis=-1)
print(c)
np.linspace(0, 10, 13, dtype='int',endpoint=False,retstep=True,axis=0)


arange: [0 2 4 6 8]
linspace: [ 0 10]
[0 0 1 2 3 3 4 5 6 6 7 8 9]


(array([0, 0, 1, 2, 3, 3, 4, 5, 6, 6, 7, 8, 9]), 0.7692307692307693)

### like linspace there are 
### geomspace where number evenly spaced on a log scale (a geometric progression)
### logspacenumber evenly spaced on log scale

In [22]:
# identity matrix
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [28]:
# rand will get values of random numbers of uniform distribution
# range [0,1)
print(np.random.rand(2,3))
np.random.rand(3)

[[0.29121788 0.37576878 0.03880248]
 [0.96130757 0.20667185 0.03730002]]


array([0.81604523, 0.09262912, 0.03239999])

In [31]:
# randn is standard normal distribution where mean is 0 and S.D is 1
# this will have negative numbers too
print(np.random.randn(3))
print(np.random.randn(2,3))


[-1.75105138  0.46777969 -0.3823016 ]
[[-0.4237632   1.04598604 -1.57480138]
 [-0.80543611 -0.65916484 -0.85044729]]


In [35]:
# np.random.randint(low, high=..., size=..., dtype=...)
print(np.random.randint(0, 101,(2,3)))
np.random.randint(0,101,5)


[[80 84 54]
 [71 97 48]]


array([68, 91, 82, 17, 15])

## random.seed is used to get the same values in case u need it again
### see below three cells

In [39]:
np.random.seed(42)
np.random.rand(4)

hbc [0.37454012 0.95071431 0.73199394 0.59865848]


array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [37]:
np.random.rand(4)


array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [40]:
np.random.seed(42)
np.random.rand(4)
# the below value is same as the output of above cell i.e first cell of random.seed

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [41]:
arr = np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
randarray = np.random.randint(0,101,10)
print(randarray)
print(randarray.max())
randarray.min()

[57 21 88 48 90 58 41 91 59 79]
91


21

In [46]:
# the argmax gives the index location of the max value
print(randarray.argmin())
randarray.argmax()


1


7